### ISSUE TITLE
HELP!!!!

### ISSUE THREAD

**Issue by ismelferrer** [TheFe91/flutter_keycloak#2]
This code 
`await _flutterKeycloak.login(
        {
          'url': 'https://my-keycloak-url/auth',
          'realm': 'my-realm',
          'clientId': 'my-client-id',
        },
        'user',
        'pass',
        scope: 'openid profile',
      );`
give me this error 
`type 'Null' is not a subtype of type 'String'`

**Comment by TheFe91** [comment]
You should give a minimum reproducible example and add more details. Otherwise it is impossible to help you

**Comment by ismelferrer** [comment]
final FlutterKeycloak _flutterKeycloak = FlutterKeycloak();

  void _login(String username, String password) async {
    try {
      await _flutterKeycloak.login(
        { 'url': 'http://192.168.114.59:8080/auth', 'realm': 'TEST', 'clientId': 'test', },             // ID del cliente
        username,
        password,
      );
      print("Login exitoso");
    } catch (e) {
      print("Error en login: $e");
    }
  }

this is the code of my login function in my local keycloak client and "I/flutter (14348): Error en login: type 'Null' is not a subtype of type 'String'" is the error

**Comment by TheFe91** [comment]
As you can see by inspecting the code at lines 26-29 of `lib/flutter_keykloak.dart`, the `conf` object needs to have the following keys:

- resource
- realm
- credentials
- authServerUrl

but yours has

- url
- realm
- clientId

which is totally incompatible with the required one.

Maybe creating a dedicated `Config` class could help, I'll look at that as soon as I have time.

Closing
